name: Publish to Comfy registry
on:
  workflow_dispatch:
  push:
    branches:
      - main          # 如果你的默认分支是 master，请改为 master
    paths:
      - "pyproject.toml"

jobs:
  publish-node:
    name: Publish Custom Node to registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v5
      - name: Publish Custom Node
        uses: Comfy-Org/publish-node-action@v1   # 使用稳定版本 v1
        with:
          personal_access_token: ${{ secrets.REGISTRY_ACCESS_TOKEN }}
